# -- Basic Settings ------------------------------------------
set -g prefix C-a
set -g escape-time 500
set -g history-limit 5000
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
set -g default-terminal "tmux-256color"
set -g extended-keys on
set -g extended-keys-format csi-u
# -- Status Bar ---------------------------------------------
set -g status-position top
set -g status-interval 1
set -g status-left "#{session_name} "

# bind keys
bind-key u run-shell '~/.config/tmux/popuptmux'
bind-key M-g display-popup -E -d "#{pane_current_path}" -w 90% -h 90% lazygit
bind-key M-b display-popup -E -d "#{pane_current_path}" -w 90% -h 90% btop
bind-key M-, source ~/.config/tmux/tmux.conf \; display-message "Tmux configuration reloaded!"

# -- Plugins -----------------------------------------------
# Plugin manager

# Theme
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'

# Theme configuration

set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"

# CUSTOM THEME

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

run '~/.config/tmux/plugins/tmux/catppuccin.tmux'
# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_session}"
#set -gF status-right "#{E:@catppuccin_status_cpu}#{E:@catppuccin_status_ram}#{E:@catppuccin_status_session}#{E:@catppuccin_status_uptime}#{E:@catppuccin_status_battery}"
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
#set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# Other plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-pain-control'

# Initialize TMUX plugin manager
# Keep this line at the very bottom of tmux.conf
set -g @plugin 'tmux-plugins/tpm'
run '~/.config/tmux/plugins/tpm/tpm'
